---
- hosts: digitalocean
  vars_files:
  - ./nnc.yml

  vars:
    scaners: "{{ lookup('file', 'scaners.txt') }}"

  tasks:

  - name: ssh key check
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=/root/nnc

  - name: ssh key check at DO
    digital_ocean: >
      state=present
      command=ssh
      name=nnc
      ssh_pub_key="{{ lookup('file', '/root/nnc.pub') }}"
      api_token={{ do_token }}
    register: nnc

  - name: create scaners
    digital_ocean: >
      state=present
      command=droplet
      name={{ item }}
      unique_name=yes
      size_id=1gb
      region_id=ams3
      image_id=debian-9-x64
      ssh_key_ids={{ nnc.ssh_key.id }}
      api_token={{ do_token }}
    with_items: "{{ scaners }}"
    register: droplet_details

  - name: Show IPs
    debug: msg="IP is {{ item.droplet.ip_address }}"
    with_items: "{{ droplet_details.results }}"

  - name: inventory
    add_host:
      name="{{ item.droplet.ip_address }}"
      groups=scaners
    with_items: "{{ droplet_details.results }}"

- hosts: scaners
  gather_facts: false
  become: true
  tasks:
  - name: Wait for port 22 to become available.
    local_action: "wait_for port=22 host={{ inventory_hostname }}"
  - name: command exec
    command: lsb_release -a
    register: ps
  - debug: var=ps

