---
- hosts: digitalocean
  vars_files:
  - ./nnc.yml

  vars:
    #do_token: "{{ lookup('file', 'nnc.txt') }}"
    scaners: "{{ lookup('file', 'scaners.txt') }}"
    ansible_ssh_user: "root"

  tasks:

  - name: ssh key check
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file="/opt/key/nnc"
    register: user

  - name: ssh key check at DO
    digital_ocean: >
      state=present
      command=ssh
      name=nnc
      ssh_pub_key="{{ lookup('file', '/opt/key/nnc.pub' ) }}"
      api_token={{ do_token }}
    register: nnc

  - name: create scaners
    digital_ocean: >
      state=present
      command=droplet
      name={{ item }}
      unique_name=yes
      size_id=1gb
      region_id=ams3
      image_id=debian-9-x64
      ssh_key_ids="{{ nnc.ssh_key.id }}"
      api_token={{ do_token }}
    with_items: "{{ scaners }}"
    register: droplet_details

  - name: Show IPs
    debug: msg="IP is {{ item.droplet.ip_address }}"
    with_items: "{{ droplet_details.results }}"

  - name: inventory
    add_host:
      name="{{ item.droplet.ip_address }}"
      groups=scaners
      ansible_ssh_private_key_file="{{ user.ssh_key_file }}"
    with_items: "{{ droplet_details.results }}"

- hosts: scaners
  gather_facts: true
  become: true
  remote_user: root
  #ansible_ssh_private_key_file="{{ user.ssh_key_file }}"
  tasks:

  - name: Wait for port 22 to become available.
    local_action: "wait_for port=22 host={{ inventory_hostname }}" 

  - name: print inventory
#    debug: msg="Scaner {{ ansible_ssh_host }} have IP address {{ inventory_hostname }}"
    debug: var=inventory_hostname

#  - name: dump inventory
#    local_action: "shell /usr/bin/ansible-inventory --list -i scaners"

#  - name: ifconfig
#    script: rc.ip
